name: Homolog Continuous Delivery

on:
  push:
    branches: 
      - develop
      
jobs:
  build:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          name: fga-eps-mds/2020.1-Minacademy-BackEnd/server
          tags: homolog
          workdir: server
          default_branch: develop
          dockerfile: prod.Dockerfile

  deploy:
    name: Deploy package to DigitalOcean 
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy package to DigitalOcean
        uses: appleboy/ssh-action@master
        env:
            GITHUB_USERNAME: ${{ github.actor }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.HOMOLOG_IP }}
          username: ${{ secrets.HOMOLOG_USERNAME }}
          password: ${{ secrets.HOMOLOG_PASSWORD }}
          envs: GITHUB_USERNAME, GITHUB_TOKEN
          script: |
            cd minacademy-backend
            docker login docker.pkg.github.com -u $GITHUB_USERNAME -p $GITHUB_TOKEN
            docker pull docker.pkg.github.com/fga-eps-mds/2020.1-minacademy-backend/server:homolog
            docker-compose -f docker-compose-hom.yml up -d

      

